- name: Declare variable at Play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
        
- name: Declare variable at task level
  hosts: all
  connection: local
  tasks:
    - name: Access a variable at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
       URL: TASK.EXAMLP.COM